### ISSUE TITLE
17 - Create homepage

### ISSUE THREAD

**Issue by firity** [HYF-Connect/hyf-connect#31]
[HOME PAGE](https://www.figma.com/file/MpfNES0KuBUkkd0Qk4EyOc/HYF-Connect-Wireframe?node-id=81%3A9)

#### Create a Banner section
- [x] Create a div container class:
- [x] Add an image on the left side of the banner
- [x] Add a h1 title
- [x] Add a paragraph
- [x] A button linked to `join us` page

#### Create a Core Values section
- [x] Create a div container class:
- [x] Add a h2 tittle
- [x] Add 3 images
- [x] Add 3 paragraphs 

#### Create a Projects section
- [x] Creates a div container class:
- [x] Add a h3 title
- [x] Add a h2 title
- [x] Create a carousel (slide show) to show images of 5 projects

#### Create a Testimonials section
- [x] Create a div container class:
- [x] Add a h2 title
- [x] Create 3 div
- [x] Insert 3 double quotes assets
- [x] Insert 3 paragraphs containing the testimonials
- [x] Insert 3 images of the alumni profile
- [x] Add a button linked to members page

**Comment by RosaMoran** [comment]
@yoshimalaise  here you can see his process on part of homepage and @Hajir-pro  is working on footer component and @firity  make the part of header, I think, @inggritenovaleta is working in other part and I in Contact us part
