### ISSUE TITLE
23 - Create contact-us page

### ISSUE THREAD

**Issue by firity** [HYF-Connect/hyf-connect#51]
[CONTACT US](https://www.figma.com/file/MpfNES0KuBUkkd0Qk4EyOc/HYF-Connect-Wireframe?node-id=22%3A96)

## `Must have` 

- [x] Footer component 
- [x] Header component 
- [x] Label with a question and Contact us
- [x] Picture 
- [x] Label or  object with client personal info and message to us 
- [x] Button submit

**Comment by RosaMoran** [comment]
I'll put it in pause ok because I'll start to work on footer part

**Comment by RosaMoran** [comment]
I'm testing that why i'm late
