### ISSUE TITLE
26 - Create avatar-page 

### ISSUE THREAD

**Issue by firity** [HYF-Connect/hyf-connect#54]
[AVATER](https://www.figma.com/file/MpfNES0KuBUkkd0Qk4EyOc/HYF-Connect-Wireframe?node-id=455%3A320)

**Comment by firity** [comment]
[Avater](https://www.figma.com/file/MpfNES0KuBUkkd0Qk4EyOc/HYF-Connect-Wireframe?node-id=455%3A320)

**Comment by lauraramirez220612** [comment]
html and css done but there are mistakes in css that Firewyne is helpin to solve,  tomorrow we will continue.
It is my css code;
**.avatar-container{
    Width: 419px
    Height: 570px
    border-radius: 20%;
    Top: -961px
    Left: 5338px
    Blend:Pass through
    position: absolute;
    width: 419px;
    height: 570px;
    background: #FFFFFF;
    box-shadow: 4px 4px 4px rgba(28, 34, 148, 0.25);
    border-radius: 20px;
}
.avatar-banner{
    Height: 91px
    Top: -907px
    Left: 5338px
    Blend: Pass through
    position: absolute;
    width: 419px;
    height: 91px;
    background: #DFD7EF;
    box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
}
.profile-photo{
    border-radius: 50%;
    Width: 156px
    Height: 142px
    Top: -929px
    Left: 5373px
    Blend: Pass through
    position: absolute;
    width: 156px;
    height: 142px;
    background: url(firewyni.jpeg)
}
.avatar-links{
    position: absolute;
    width: 230px;
    height: 38px;
    font-family: Poppins;
    font-style: normal;
    font-weight: 500;
    font-size: 20px;
    line-height: 133%;
    /* or 27px */
    display: flex;
    align-items: center;
    color: #000000;
}
.sign-out-btn{
    position: absolute;
    width: 192px;
    height: 54px;
    background: #2F195F;
    border-radius: 15px;
    position: absolute;
    width: 97px;
    height: 32px;
    margin-left: 118px;
    margin-right: 119px;
    margin-top: 270px;
    margin-bottom: 40px;
    font-family: Poppins;
    font-style: normal;
    font-weight: normal;
    font-size: 24Spx;
    line-height: 32;
    display: flex;
    align-items: center;
    text-align: center;
    color: #FFFFFF;_**

**Comment by lauraramirez220612** [comment]
RESULT IS.
![image](https://user-images.githubusercontent.com/67869221/147861646-2c44295f-9924-4f01-90ee-9d62e97f381b.png)

AND SHOULD BE LIKE THIS
![image](https://user-images.githubusercontent.com/67869221/147861721-c2869d15-3411-4d99-9527-08850fb320ff.png)

**Comment by lauraramirez220612** [comment]
👍
